name: Node.js CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Specify the Node.js version

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build
      run: npm run build  # Run the build script if you have one

    - name: Deploy
      run: |
        # Commands for deployment go here
        # Example: Deploy to Heroku
        # heroku deploy:jar --app your-heroku-app
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
